oriedita/oriedita

- src/main/java/origami/crease_pattern/worker/HierarchyList_Worker.java
- src/main/java/origami/folding/HierarchyList.java
- src/main/java/origami/folding/element/SubFace.java
- src/main/java/origami/folding/util/EquivalenceCondition.java
All algorithms remain the same, only the implementations are greatly improved.
In one of my tests, the folding time goes from 4531855 msec to only 299366, which is 15x faster.
> Improve folding speed

- src/main/java/origami/crease_pattern/worker/HierarchyList_Worker.java
The changes I made last time actually made step 3 slower than the original Orihime; this commit fixes the issue and also makes it slightly faster than the origin as well.
> Improve performance on folding step 3

- src/main/java/origami_editor/editor/Canvas.java
Gives problems on mac
Fixes #104
> Remove scroll undo

- src/main/java/origami/crease_pattern/FoldLineSet.java
- src/main/java/origami/crease_pattern/LineSegmentSet.java
- src/main/java/origami/crease_pattern/PointSet.java
- src/main/java/origami/crease_pattern/worker/WireFrame_Worker.java
- src/main/java/origami/data/save/LineSegmentSave.java
- src/main/java/origami/data/save/PointSave.java
- src/main/java/origami_editor/editor/App.java
- src/main/java/origami_editor/editor/Save.java
- src/main/java/origami_editor/editor/canvas/CreasePattern_Worker.java
- src/main/java/origami_editor/editor/canvas/MouseHandlerCreaseCopy.java
- src/main/java/origami_editor/editor/canvas/MouseHandlerCreaseCopy4p.java
- src/main/java/origami_editor/editor/canvas/MouseHandlerCreaseMove.java
- src/main/java/origami_editor/editor/canvas/MouseHandlerCreaseMove4p.java
Remove links between origami and origami_editor
> Refactor saving

- src/main/java/origami/crease_pattern/worker/FoldedFigure_Worker.java
- src/main/java/origami/folding/element/SubFace.java
This PR fixes some bugs in the implementation of self-intersection indication.
> Fix self-intersection indication

- src/main/java/origami/crease_pattern/worker/FoldedFigure_Worker.java
- src/main/java/origami_editor/editor/canvas/MouseHandlerModifyCalculatedShape.java
- src/main/java/origami_editor/editor/folded_figure/FoldedFigure.java
By moving `calculateFromTopCountedPosition` outside the render loop.
> Improve folded figure render performance

- src/main/java/origami/crease_pattern/element/LineSegment.java
- src/main/java/origami_editor/editor/App.java
- src/main/java/origami_editor/editor/folded_figure/FoldedFigure.java
- src/main/resources/help.properties
- src/main/resources/help_jp.properties
This PR mainly fixes the S_face tool; it also have some refactoring. The thing about reusing color instance is that (believe it or not) it saves quite some memory for large CP.
> Fix S_face tool

- src/main/java/origami_editor/editor/App.java
- src/main/java/origami_editor/editor/BottomPanel.java
- src/main/java/origami_editor/editor/Canvas.java
- src/main/java/origami_editor/editor/LeftPanel.java
- src/main/java/origami_editor/editor/canvas/CreasePattern_Worker.java
- src/main/java/origami_editor/editor/task/FoldingEstimateTask.java
- src/main/java/origami_editor/editor/task/TaskExecutor.java
Show the number of cAMV errors in the top right, so that you cannot accidentally miss one
> Improve cAMV

- src/main/java/origami/crease_pattern/worker/WireFrame_Worker.java
- src/main/java/origami/folding/FoldedFigure.java
- src/main/java/origami_editor/editor/drawing/FoldedFigure_Drawer.java
- src/main/java/origami_editor/editor/drawing/WireFrame_Worker_Drawer.java
- src/test/java/origami/folding/FoldingTest.java
This PR fixes the starting face functionality that was broken during refactoring.
> Fix starting face

- src/main/java/origami_editor/editor/BottomPanel.java
- src/main/java/origami_editor/editor/canvas/CreasePattern_Worker.java
- src/main/java/origami_editor/editor/task/CheckCAMVTask.java
- src/main/java/origami_editor/editor/task/FinishedFuture.java
- src/main/java/origami_editor/editor/task/FoldingEstimateSave100Task.java
- src/main/java/origami_editor/editor/task/TaskExecutor.java
> cAMV in own thread

- src/main/java/origami_editor/editor/canvas/MouseHandlerCreaseCopy4p.java
> Fix cp_4p tool

- src/main/java/origami_editor/editor/App.java
- src/main/java/origami_editor/editor/AppMenuBar.java
- src/main/java/origami_editor/editor/BottomPanel.form
- src/main/java/origami_editor/editor/BottomPanel.java
- src/main/java/origami_editor/editor/Canvas.java
- src/main/java/origami_editor/editor/LeftPanel.java
- src/main/java/origami_editor/editor/TopPanel.java
- src/main/java/origami_editor/editor/canvas/MouseHandlerChangeStandardFace.java
- src/main/java/origami_editor/editor/canvas/MouseHandlerModifyCalculatedShape.java
- src/main/java/origami_editor/editor/canvas/MouseHandlerMoveCalculatedShape.java
- src/main/java/origami_editor/editor/canvas/MouseHandlerMoveCreasePattern.java
- src/main/java/origami_editor/editor/databinding/ApplicationModel.java
- src/main/java/origami_editor/editor/drawing/FoldedFigure_Drawer.java
- src/main/java/origami_editor/editor/drawing/FoldedFigure_Worker_Drawer.java
- src/main/java/origami_editor/editor/export/Svg.java
- src/main/java/origami_editor/editor/task/FoldingEstimateSave100Task.java
- src/main/java/origami_editor/editor/task/FoldingEstimateSpecificTask.java
- src/main/java/origami_editor/editor/task/FoldingEstimateTask.java
- src/main/java/origami_editor/editor/task/TwoColoredTask.java
Displays a combobox in the bottom left which can be used to switch between different folded figures. Also refactors how folded figures are created and updated.
> Folded figure list

- src/main/java/origami/folding/permutation/ChainPermutationGenerator.java
- src/test/java/origami/folding/FoldingSolutionsTest.java
It's a tiny bug that causes big difference.
> Fixed missing alternative solutions

- src/main/java/origami_editor/editor/App.java
> Update file extension when changing filefilter in filechooser

- src/main/java/origami_editor/editor/App.java
- src/main/java/origami_editor/editor/LeftPanel.java
- src/main/java/origami_editor/editor/canvas/CreasePattern_Worker.java
- src/main/java/origami_editor/editor/databinding/CanvasModel.java
> Toggle line color with control

- src/main/java/origami/crease_pattern/worker/WireFrame_Worker.java
- src/main/java/origami/folding/FoldedFigure.java
- src/main/java/origami_editor/editor/App.java
- src/main/java/origami_editor/editor/Canvas.java
- src/main/java/origami_editor/editor/canvas/MouseHandlerChangeStandardFace.java
- src/main/java/origami_editor/editor/canvas/MouseHandlerModifyCalculatedShape.java
- src/main/java/origami_editor/editor/drawing/FoldedFigure_Drawer.java
- src/main/java/origami_editor/editor/drawing/WireFrame_Worker_Drawer.java
- src/main/java/origami_editor/editor/task/FoldingEstimateSave100Task.java
- src/main/java/origami_editor/editor/task/FoldingEstimateSpecificTask.java
- src/main/java/origami_editor/editor/task/FoldingEstimateTask.java
- src/main/java/origami_editor/editor/task/TwoColoredTask.java
- src/test/java/origami/folding/FoldingSolutionsTest.java
- src/test/java/origami/folding/FoldingTest.java
There is now `startingFaceId` in FoldedFigure_Drawer, which is read every time the model is folded, this value can be changed externally. By default it's the face containing 0,0 or if that doesn't exist it chooses face `1` as the starting face.
> Refactor S_face

- src/main/java/origami/crease_pattern/worker/FoldedFigure_Configurator.java
- src/main/java/origami/crease_pattern/worker/FoldedFigure_Worker.java
- src/main/java/origami/folding/FoldedFigure.java
- src/main/java/origami/folding/element/SubFace.java
This PR moves the code related to configurating `FoldedFigure_worker` to a separate class `FoldedFigure_configurator` for better organizing, and it also breaks `HierarchyList_configure` down to several functions.
> Refactor FoldedFigure_Worker

- src/main/java/origami_editor/editor/BottomPanel.java
- src/main/java/origami_editor/editor/Canvas.java
- src/main/java/origami_editor/editor/canvas/CreasePattern_Worker.java
- src/main/java/origami_editor/editor/databinding/CanvasModel.java
- src/main/java/origami_editor/editor/databinding/FileModel.java
- src/main/java/origami_editor/editor/service/FileSaveService.java
- src/main/java/origami_editor/editor/task/FoldingEstimateSave100Task.java
- src/test/java/origami_editor/editor/save/SaveTest.java
> Fix double buffer, rework image export

- src/main/java/origami_editor/editor/drawing/FoldedFigure_Drawer.java
Fix the bug that X-ray button triggers exception if clicked immediately after openning a file.
> Fix X-ray button

- src/main/java/origami/crease_pattern/FoldLineSet.java
- src/main/java/origami/data/quadTree/adapter/LineSegmentListAdapter.java
- src/main/java/origami/data/quadTree/collector/PointCollector.java
This fixes the rounding bug in the previous smart-folding implementation.
> Fix smart-folding with QuadTree

- src/main/java/origami_editor/editor/BottomPanel.java
- src/main/java/origami_editor/editor/LeftPanel.java
- src/main/java/origami_editor/editor/RightPanel.java
- src/main/java/origami_editor/editor/TopPanel.java
- src/main/java/origami_editor/editor/component/FoldedFigureResize.java
- src/main/java/origami_editor/editor/component/FoldedFigureRotate.java
> Press enter to commit values

- src/main/java/origami/crease_pattern/LineSegmentSet.java
- src/main/java/origami/crease_pattern/worker/FoldedFigure_Configurator.java
- src/main/java/origami/data/quadTree/comparator/QuadTreeComparator.java
- src/main/java/origami/folding/HierarchyList.java
- src/main/java/origami/folding/algorithm/AdditionalEstimationAlgorithm.java
- src/main/java/origami/folding/element/SubFace.java
- src/main/java/origami/folding/permutation/ChainPermutationGenerator.java
- src/main/java/origami/folding/permutation/combination/CombinationGenerator.java
This PR contains:
1. Optimizing preparations stages by making more steps parallel, and improve the parameters of QuadTree to make it more effective.
2. Fix several critical bugs in the CombinationGenerator that potentially could lead to skipping of valid solutions.
3. Improve the algorithm of reduceSubFaceSet(). Now Ryujin runs in sub-2-minute.
> Preparation optimization and fix CombinationGenerator

- src/main/java/oriedita/editor/action/MouseHandlerCreaseCopy.java
- src/main/java/oriedita/editor/action/MouseHandlerCreaseCopy4p.java
- src/main/java/oriedita/editor/action/MouseHandlerCreaseMove.java
- src/main/java/oriedita/editor/action/MouseHandlerCreaseMove4p.java
- src/main/java/oriedita/editor/action/MouseHandlerDrawCreaseSymmetric.java
- src/main/java/oriedita/editor/action/MouseHandlerLengthenCrease.java
- src/main/java/oriedita/editor/canvas/CreasePattern_Worker.java
- src/main/java/origami/crease_pattern/FoldLineSet.java
- src/main/java/origami/crease_pattern/PointLineMap.java
- src/main/java/origami/data/quadTree/QuadTree.java
- src/main/java/origami/data/quadTree/adapter/DivideAdapter.java
- src/main/java/origami/data/quadTree/adapter/LineSegmentListAdapter.java
- src/main/java/origami/data/quadTree/adapter/PointLineMapAdapter.java
- src/main/java/origami/data/quadTree/collector/LineSegmentCollector.java
This PR improves the performance of "delete all extra vertices" and `divideLineSegmentIntersections()` which is used in many actions such as copy, move etc.
> Improve editing performance

- src/main/java/oriedita/editor/Canvas.java
- src/main/java/oriedita/editor/databinding/BackgroundModel.java
- src/main/java/oriedita/editor/service/FileSaveService.java
- src/main/java/oriedita/editor/swing/TopPanel.form
- src/main/java/oriedita/editor/swing/TopPanel.java
> Improve background loading

- .github/workflows/maven.yml
- .github/workflows/pull-request.yml
- .github/workflows/release.yml
- pom.xml
Java 8 was giving problems anyways
> Set jdk to 11

- src/main/java/oriedita/editor/action/MouseHandlerCreasesAlternateMV.java
- src/main/java/oriedita/editor/action/MouseHandlerFlatFoldableCheck.java
- src/main/java/oriedita/editor/action/MouseHandlerLengthenCrease.java
- src/main/java/origami/Epsilon.java
- src/main/java/origami/crease_pattern/FoldLineSet.java
- src/main/java/origami/crease_pattern/OritaCalc.java
- src/main/java/origami/crease_pattern/element/Polygon.java
This PR fixes the problem that cAMV becomes too sensitive for some CPs after #172 .
> Fix cAMV sensitivity

- src/main/java/origami/crease_pattern/OritaCalc.java
- src/main/java/origami/crease_pattern/element/Polygon.java
- src/main/java/origami/crease_pattern/worker/FoldedFigure_Configurator.java
This PR fixes a critical rounding error that could lead to completely wrong (and even self-intersecting) stacking solution at the end.
> Fix critical rounding error

- oriedita/src/main/java/oriedita/editor/App.java
- oriedita/src/main/java/oriedita/editor/Canvas.java
- oriedita/src/main/java/oriedita/editor/Oriedita.java
- oriedita/src/main/java/oriedita/editor/action/MouseHandlerCircleDrawConcentricSelect.java
- oriedita/src/main/java/oriedita/editor/action/MouseHandlerCircleDrawConcentricTwoCircleSelect.java
- oriedita/src/main/java/oriedita/editor/action/MouseHandlerModifyCalculatedShape.java
- oriedita/src/main/java/oriedita/editor/drawing/tools/DrawingUtil.java
- oriedita/src/main/java/oriedita/editor/export/Fold.java
- oriedita/src/main/java/oriedita/editor/export/Obj.java
- oriedita/src/main/java/oriedita/editor/service/ButtonService.java
- oriedita/src/main/java/oriedita/editor/swing/BottomPanel.java
- oriedita/src/main/java/oriedita/editor/swing/LeftPanel.java
- oriedita/src/main/java/oriedita/editor/swing/RightPanel.java
- oriedita/src/main/java/oriedita/editor/swing/dialog/ExportDialog.java
- oriedita/src/main/java/oriedita/editor/tools/ResourceUtil.java
- origami/src/main/java/origami/Epsilon.java
- origami/src/main/java/origami/crease_pattern/FoldLineSet.java
- origami/src/main/java/origami/crease_pattern/OritaCalc.java
- origami/src/main/java/origami/crease_pattern/PointSet.java
- origami/src/main/java/origami/crease_pattern/worker/FoldedFigure_Configurator.java
- origami/src/main/java/origami/folding/element/SubFace.java
This PR contains two things:
1. Fix the precision of isInside_sweet again to fix folding errors in additional samples.
2. Fix all minor coding issues suggested by VS Code Java linting, including:
- Remove unused import.
- Comment out unused variables and private methods (I keep them as comments just in case).
- Add default clauses to switch.
- Close JarFile to prevent potential memory leak.
- Add missing generic parameters.
> Fixing precision and refactoring

- oriedita/src/main/resources/tinylog.properties
This PR adds color and formats time for better loggin clarity. It requires clean and rebuild the project to take effect.
> Add color to log and format time

- origami/src/main/java/origami/crease_pattern/worker/FoldedFigure_Configurator.java
- origami/src/main/java/origami/crease_pattern/worker/FoldedFigure_Worker.java
- origami/src/main/java/origami/folding/FoldedFigure.java
- origami/src/main/java/origami/folding/element/SubFace.java
- origami/src/main/java/origami/folding/permutation/ChainPermutationGenerator.java
- origami/src/main/java/origami/folding/permutation/PermutationGenerator.java
In this PR I fixed the bottom constraints handling, so that everything works properly when tested with the sample cp file provided in oriedita@98ac37c.
@undertrox please help me review the changes.
> Fix bottom constraints handling

- oriedita/src/main/java/oriedita/editor/App.java
- oriedita/src/main/java/oriedita/editor/databinding/ApplicationModel.java
- oriedita/src/main/java/oriedita/editor/service/ButtonService.java
- oriedita/src/main/java/oriedita/editor/swing/AppMenuBar.java
- oriedita/src/main/java/oriedita/editor/swing/Editor.java
Scaf asked for this, it's useful for people with smaller screens or when using oriedita in split-screen with other programs.
> Allow for Hiding and showing of panels

- oriedita-data/src/main/java/oriedita/editor/service/impl/DequeHistoryState.java
the undo states are now compressed, and the amount of undo steps is adjusted based on how much memory is available
> fix running out of memory when working on big files for too long

- oriedita-data/src/main/java/oriedita/editor/databinding/ApplicationModel.java
- oriedita-ui/src/main/java/oriedita/editor/swing/AppMenuBar.java
- oriedita-ui/src/main/java/oriedita/editor/swing/dialog/PreferenceDialog.form
- oriedita-ui/src/main/java/oriedita/editor/swing/dialog/PreferenceDialog.java
- Remove ck4Slider
- Enable zoom snap
- Set minimum pref window size
> Minor pref change

- oriedita-ui/src/main/java/oriedita/editor/swing/BottomPanel.java
- oriedita-ui/src/main/java/oriedita/editor/swing/InputEnterKeyAdapter.java
- oriedita-ui/src/main/java/oriedita/editor/swing/LeftPanel.java
- oriedita-ui/src/main/java/oriedita/editor/swing/RightPanel.java
- oriedita-ui/src/main/java/oriedita/editor/swing/TopPanel.java
- oriedita-ui/src/main/java/oriedita/editor/swing/component/FoldedFigureResize.java
- oriedita-ui/src/main/java/oriedita/editor/swing/component/FoldedFigureRotate.java
- oriedita-ui/src/main/java/oriedita/editor/swing/dialog/PreferenceDialog.java
- Implement InputEnterKeyAdapter to the panels
- Fix dark warning popup in Mac pref window and show it first before applying
- Remove Ok and Cancel warnings
> Various tweaks

- oriedita-common/src/main/java/oriedita/editor/canvas/LineStyle.java
- oriedita-data/src/main/java/oriedita/editor/Colors.java
- oriedita-ui/src/main/java/oriedita/editor/drawing/tools/DrawingUtil.java
- oriedita-ui/src/main/java/oriedita/editor/swing/dialog/PreferenceDialog.form
- oriedita-ui/src/main/java/oriedita/editor/swing/dialog/PreferenceDialog.java
- oriedita/src/main/java/oriedita/editor/export/Svg.java
- origami/src/main/java/origami/crease_pattern/element/LineColor.java
**Light mode:**
**Dark mode:**
Obviously, the dark mode doesn't like black n white with the grid on too much but I tried to get to a good compromise between the file line colors and the grid colors. Any feedback is appreciated.
> Black & white solid line style

- oriedita-data/src/main/java/oriedita/editor/databinding/ApplicationModel.java
- oriedita-ui/src/main/java/oriedita/editor/swing/dialog/PreferenceDialog.form
- oriedita-ui/src/main/java/oriedita/editor/swing/dialog/PreferenceDialog.java
- oriedita/src/main/java/oriedita/editor/canvas/impl/CreasePattern_Worker_Impl.java
add a setting to change how far the mouse will "snap" to near points/lines
> add Mouse radius setting

- oriedita-ui/src/main/java/oriedita/editor/Canvas.java
- oriedita-ui/src/main/java/oriedita/editor/action/DuplicateFoldedModelAction.java
- Remove Wireframe & Xray from the right click for 2-colored CP
- Fix duplicate not working for 2-colored CP
https://user-images.githubusercontent.com/94136126/227256127-15c350d8-e8bd-4282-928c-d974a22b3112.mp4
> Right Click 2 Colored CP Fix & Tweak

- oriedita-data/src/main/java/oriedita/editor/canvas/CreasePattern_Worker.java
- oriedita-ui/src/main/java/oriedita/editor/Canvas.java
- oriedita-ui/src/main/java/oriedita/editor/swing/LeftPanel.java
- oriedita/src/main/java/oriedita/editor/canvas/impl/CreasePattern_Worker_Impl.java
- oriedita/src/main/java/oriedita/editor/handler/MouseHandlerCreaseCopy.java
- oriedita/src/main/java/oriedita/editor/handler/MouseHandlerCreaseCopy4p.java
- oriedita/src/main/java/oriedita/editor/handler/MouseHandlerCreaseMove.java
- oriedita/src/main/java/oriedita/editor/handler/MouseHandlerCreaseMove4p.java
- oriedita/src/main/java/oriedita/editor/handler/MouseHandlerCreaseSelect.java
- oriedita/src/main/java/oriedita/editor/handler/MouseHandlerDrawCreaseSymmetric.java
- oriedita/src/main/java/oriedita/editor/handler/MouseHandlerLineSegmentDelete.java
- oriedita/src/main/resources/help.properties
- origami/src/main/java/origami/crease_pattern/FoldLineSet.java
Make it easier to exit selection tools when presented with an empty advance
selection. Also add support for warning messages.
1) 4 point move tool: point G should be point C
2) Lengthen crease line (Specified color) tool: Help is hidden due to a syntax typo
> Fixes Issue#325 - UI and Documentation Improvements

- oriedita-data/src/main/java/oriedita/editor/databinding/GridModel.java
- oriedita-ui/src/main/java/oriedita/editor/swing/LeftPanel.java
- oriedita/src/main/resources/help.properties
- oriedita/src/main/resources/help_jp.properties
- origami/src/main/java/origami/Epsilon.java
https://github.com/oriedita/oriedita/assets/64196922/8823072d-715e-42eb-8cea-a86b9dd41cda
> Adds support for angles > 180 and snapping to lower and upper limits of grid angle range

- oriedita-data/src/main/java/oriedita/editor/databinding/ApplicationModel.java
- oriedita-ui/src/main/java/oriedita/editor/swing/LeftPanel.form
- oriedita-ui/src/main/java/oriedita/editor/swing/LeftPanel.java
- oriedita-ui/src/main/java/oriedita/editor/swing/RightPanel.java
- oriedita/src/main/java/oriedita/editor/service/impl/FoldingServiceImpl.java
this checkbox has been basically unusable for quite some time (see #264), and only caused issues, so I think it's safe to remove.
> remove Correct checkbox

- .idea/uiDesigner.xml
- oriedita-ui/src/main/java/oriedita/editor/swing/CollapsiblePanel.java
- oriedita-ui/src/main/java/oriedita/editor/swing/dialog/PreferenceDialog.java
...which takes a string as a header and the panel that holds whatever the content is. Updated the PreferenceDialog to use that.
Also made the collapsible panel to open by default to properly expand the panel it's in to prevent being cut off
> Custom Collapsible Panel

- .github/workflows/pull-request.yml
- .idea/misc.xml
Build create artifact pipeline with all supported java versions, so that we can easily stop supporting older versions.
> Build for multiple versions

- oriedita-data/src/main/java/oriedita/editor/databinding/ApplicationModel.java
- oriedita-ui/src/main/java/oriedita/editor/CanvasUI.java
- oriedita-ui/src/main/java/oriedita/editor/drawing/tools/DrawingUtil.java
- oriedita-ui/src/main/java/oriedita/editor/handler/DrawingSettings.java
- oriedita-ui/src/main/java/oriedita/editor/swing/dialog/PreferenceDialog.form
- oriedita-ui/src/main/java/oriedita/editor/swing/dialog/PreferenceDialog.java
- oriedita/src/main/java/oriedita/editor/canvas/impl/CreasePattern_Worker_Impl.java
- oriedita/src/main/java/oriedita/editor/handler/BaseMouseHandlerLineTransform.java
- oriedita/src/main/java/oriedita/editor/handler/MouseHandlerAngleSystem.java
- oriedita/src/main/java/oriedita/editor/handler/MouseHandlerSymmetricDraw.java
- origami/src/main/java/origami/crease_pattern/element/LineSegment.java
> improve line drawing for thick lines

- oriedita-data/src/main/java/oriedita/editor/export/FoldExporter.java
> Fix exporting cp/fold with errors

- oriedita-data/src/main/java/oriedita/editor/export/FoldExporter.java
> Additional fix for export

- oriedita/src/main/java/oriedita/editor/handler/MouseHandlerParallelDraw.java
- oriedita/src/main/java/oriedita/editor/handler/MouseHandlerSymmetricDraw.java
symmetricDraw: made sure to also set Color
parallelDraw: fix the tool not drawing the right line because change in a `lineStep` doesn't update the `LineSegment` var assigned with it for some reason
> Fix symmetricDraw and parallelDraw

- oriedita-ui/src/main/java/oriedita/editor/swing/dialog/HelpDialog.java
- oriedita-ui/src/main/java/oriedita/editor/swing/dialog/PreferenceDialog.form
- oriedita-ui/src/main/java/oriedita/editor/swing/dialog/PreferenceDialog.java
A search bar that provides live update of the hotkey lists to whatever you type in the search bar. Mainly for easy (or easier) navigation
https://github.com/oriedita/oriedita/assets/94136126/68488ec9-47f1-403b-86b0-6804f7900066
> Search bar hotkey

- oriedita/src/main/java/oriedita/editor/handler/MouseHandlerDoubleSymmetricDraw.java
- oriedita/src/main/java/oriedita/editor/handler/MouseHandlerDrawCreaseSymmetric.java
Specifically the iterators from the commit a47ec89 .
> Temporarily fix some tools in which the new iterator causes issues

- oriedita-ui/src/main/java/oriedita/editor/action/ActionType.java
- oriedita-ui/src/main/java/oriedita/editor/swing/dialog/PreferenceDialog.form
- oriedita-ui/src/main/java/oriedita/editor/swing/dialog/PreferenceDialog.java
- oriedita-ui/src/main/java/oriedita/editor/swing/dialog/SelectKeyStrokeDialog.java
- oriedita-ui/src/main/java/oriedita/editor/tools/KeyStrokeUtil.java
https://github.com/oriedita/oriedita/assets/94136126/9fd01570-6cb3-4ad9-a359-4d63df892f32
> Option to only show key-binded actions + fix/tweaks

- oriedita-ui/src/main/java/oriedita/editor/drawing/FoldedFigure_Drawer.java
- origami/src/main/java/origami/folding/FoldedFigure.java
> Stop folding calculations from running if there's no line to fold

- oriedita-common/src/main/java/oriedita/editor/service/ButtonService.java
- oriedita-ui/src/main/java/oriedita/editor/swing/dialog/PreferenceDialog.java
- oriedita/src/main/java/oriedita/editor/service/impl/ButtonServiceImpl.java
- oriedita/src/main/java/oriedita/editor/service/impl/FileSaveServiceImpl.java
> Fix importing / restoring all defaults

- oriedita-ui/src/main/java/oriedita/editor/action/BackColorAction.java
- oriedita-ui/src/main/java/oriedita/editor/action/FrontColorAction.java
- oriedita-ui/src/main/java/oriedita/editor/action/LineColorAction.java
it has major issue with alpha slider/spinner locking up in the default color chooser panels, so this needs to be merged asap.
@undertrox
> Exclude custom hsv panel for now

- oriedita-data/src/main/java/oriedita/editor/databinding/ApplicationModel.java
- oriedita-ui/src/main/java/oriedita/editor/swing/dialog/PreferenceDialog.form
- oriedita-ui/src/main/java/oriedita/editor/swing/dialog/PreferenceDialog.java
- oriedita/src/main/java/oriedita/editor/service/impl/ResetServiceImpl.java
setting's in Preference -> Appearance
> Customizable default grid size upon launch/new document

- oriedita-ui/src/main/java/oriedita/editor/swing/LeftPanel.java
- oriedita/src/main/java/oriedita/editor/handler/MouseHandlerCreaseCopy.java
- oriedita/src/main/java/oriedita/editor/handler/MouseHandlerCreaseCopy4p.java
- oriedita/src/main/java/oriedita/editor/handler/MouseHandlerCreaseMove.java
- oriedita/src/main/java/oriedita/editor/handler/MouseHandlerCreaseMove4p.java
- oriedita/src/main/java/oriedita/editor/handler/MouseHandlerDrawCreaseSymmetric.java
> Fix persist not working on some tools

- build/02_create_release.sh
Fixes the error in releasing Mac M1 portable build.
> Fix release script for Mac M1 portable

- origami/src/main/java/origami/Epsilon.java
- origami/src/main/java/origami/crease_pattern/PointSet.java
- origami/src/main/java/origami/crease_pattern/worker/WireFrame_Worker.java
This PR further increase the precision following #459
> Further increase point precision
