oriedita/oriedita

src/main/java/origami/crease_pattern/worker/HierarchyList_Worker.java, src/main/java/origami/folding/HierarchyList.java, src/main/java/origami/folding/util/BounceDetector.java
The original Orihime algorithm chooses an initial SubFace ordering to perform the exhaustive search, but it is very commonly the case that the ordering is not optimal, leading to a phenomenon I called "bouncing", where the search hits a dead-end at a certain depth (H) and have to return to another certain depth (L) repeatedly. This suggests that SubFace H is more "relevant" to those SubFaces before L, so swapping H and L typically leads to a much faster search (in some cases 100x faster).
This BounceDetector class detects the bouncing phenomenon based on some sensitivity constants and makes the swap when it detects one.
=> Bounce detection and the swapping algorithm (with format fixed)

src/main/java/origami/crease_pattern/worker/FoldedFigure_Worker.java, src/main/java/origami/data/listMatrix/PseudoListMatrix.java, src/main/java/origami/folding/algorithm/AdditionalEstimationAlgorithm.java, src/main/java/origami/folding/algorithm/SwappingAlgorithm.java, src/main/java/origami/folding/element/SubFace.java, src/main/java/origami/folding/permutation/ChainPermutationGenerator.java
This PR improves the permutation generator and the reverse swapping strategy to better cope with CPs such as variants of Ryujin. It brings down the runtime of the fold-in-half version from 35 minutes to 17.
=> Performance improvement for super-complex CP

src/main/java/origami/crease_pattern/worker/FoldedFigure_Worker.java, src/main/java/origami/folding/element/SubFace.java
Memory profiling reveals that during the folding of Ryujin, more than 2G of memory is used on storing the faceIdMap arrays for the subfaces. Since the performance of hash maps and arrays is quite obvious in this case, it's a bad idea to swtich entirely to hash maps. By restricted the usage of array-based faceIdMap to only valid subfaces, we barely lose any speed but now Ryujin will fold with only 4G memory.
=> Memory optimization

src/main/java/origami/crease_pattern/worker/FoldedFigure_Worker.java, src/main/java/origami/folding/HierarchyList.java, src/main/java/origami/folding/element/SubFace.java
This PR stores the relevant EquivalenceConditions in corresponding SubFaces. This speed up the search pretty dang good; in particular, the runtime of fully folded Ryujin went from 16 mintues to just 5 mintues.
=> Search stage optimization

src/main/java/origami_editor/editor/App.java, src/main/java/origami_editor/editor/drawing/FoldedFigure_Worker_Drawer.java
Before this PR, the self-intersection highlighting doesn't work properly when the the folded figure is created for the first time. The user would have to turn off-and-on the option to see the hightlighting. This is because `FoldedFigure_Worker_Drawer.setData()` method is not called when individual instance is constructed.
Since self-intersection is a global option in the menu bar, it makes more sense to make `displaySsi` a static variable, and it also helps fixing this bug by hooking it up with the event listener properly.
=> Fix self-intersection highlighting

src/main/java/origami/crease_pattern/worker/FoldedFigure_Configurator.java, src/main/java/origami/crease_pattern/worker/FoldedFigure_Worker.java, src/main/java/origami/folding/HierarchyList.java, src/main/java/origami/folding/algorithm/AdditionalEstimationAlgorithm.java, src/main/java/origami/folding/element/SubFace.java
This PR disables realtime AEA for some CP in which it doesn't work. For those CPs, doing so actually makes it faster. Folded Ryujin now folds in only 76 seconds.
=> Disable realtime AEA if necessary

oriedita/src/main/java/oriedita/editor/Canvas.java
using rightclick to erase would sometimes switch between only deleting aux and only deleting fold lines, now it deletes everything again (except if youre currently using an eraser tool, then right click does the same thing as left click)
=> Fix rightclick eraser behaving weirdly

oriedita/src/main/java/oriedita/editor/canvas/CreasePattern_Worker.java, oriedita/src/main/java/oriedita/editor/databinding/ApplicationModel.java, oriedita/src/main/java/oriedita/editor/drawing/tools/DrawingUtil.java, oriedita/src/main/java/oriedita/editor/swing/AppMenuBar.java, oriedita/src/main/java/oriedita/editor/task/CheckCAMVTask.java, origami/src/main/java/origami/crease_pattern/FlatFoldabilityViolation.java, origami/src/main/java/origami/crease_pattern/FoldLineSet.java, origami/src/main/java/origami/crease_pattern/LittleBigLittleViolation.java, origami/src/main/java/origami/crease_pattern/OritaCalc.java, origami/src/main/java/origami/crease_pattern/element/LineSegment.java
cAMV now differentiates between different types of foldability errors, the same way as origamiDraw does. Theres also a setting in the view menu to get the old way back, since the new way can be easier to miss on very dense cps
=> Camv improvements

.idea/compiler.xml, oriedita/src/main/java/oriedita/editor/action/MouseHandlerPerpendicularDraw.java
Perpendicular in previous versions used to function in sequential order: select a point to begin drawing, and then a crease (**one that the point isn't lying on**) to draw properly. However, the issue (though somewhat minor) 
is that the tool doesn't do anything when selecting the crease containing the point. 
Therefore, inspired by OrigamiDraw, I decided to make a new feature that takes advantage of selecting its own crease. When the previous sequence is performed, it will **create an indicator of a new line** perpendicular to the selected crease. The user can then **select the destination crease for the new line to extend to**.
https://user-images.githubusercontent.com/94136126/170590719-42b76f9a-4d68-4711-90a7-b0f6e11015e3.mp4
=> Perpendicular tool's new feature

oriedita/src/main/java/oriedita/editor/action/MouseHandlerSquareBisector.java, origami/src/main/java/origami/crease_pattern/OritaCalc.java
Users can either do the 3-points method like the usual or the new **2-lines method** by first selecting a point or a line respectively.
It is now also possible to s**elect 2 parallel lines and draw a "bisector" parallel to those 2 lines**, making sure to select 2 more lines to define its beginning point and end point.
There are issues in with this feature and I'm aware of some of them and I don't know how to fix them right now. But it should function as intended for the most part. I hope someone else smarter than me can do this if they encounter them.
**Demonstration:**
=> Bisector tool's new features

oriedita/src/main/java/oriedita/editor/App.java, oriedita/src/main/java/oriedita/editor/service/ButtonService.java, oriedita/src/main/java/oriedita/editor/swing/dialog/SelectKeyStrokeDialog.java
this pr contains 2 small bugfixes:
- the window was sized weirdly when oriedita was started while the panels were hidden
- removing keybinds didnt work, and adding new ones needed a restart until they started working
=> Fix window size and keystrokes

oriedita-ui/src/main/java/oriedita/editor/swing/LeftPanel.java, oriedita-ui/src/main/java/oriedita/editor/swing/OnlyDoubleAdapter.java, oriedita-ui/src/main/java/oriedita/editor/swing/OnlyIntAdapter.java, oriedita-ui/src/main/java/oriedita/editor/swing/RightPanel.form, oriedita-ui/src/main/java/oriedita/editor/swing/RightPanel.java
- Hopefully solved issue #262 , now restricting inputs to integers/doubles.
- Set measured lengths and angles text fields to be uneditable since they shouldn't be in the first place.
The most significant issue about this implementation is visual. The logic is if the key inputs are not numeric and backspace (and decimal if dealing with double values), the text field will be set to be uneditable (`setEditable(false)`) and vice versa. If you type something that doesn't fit the condition (say a letter), the field will be uneditable, and its visual changes. Users might see that and think it's not interactable although it still is, which can lead to confusion. But I couldn't really think of other ways that are not complicated to implement this, so this will have to do. I still want to fix this …
=> Restricted input

oriedita-ui/src/main/java/oriedita/editor/swing/AppMenuBar.java, oriedita-ui/src/main/java/oriedita/editor/swing/dialog/PreferenceDialog.java
- The Pref window should now only be viewed as one window and unable to make duplicate windows by abusing the switching to light and dark mode.
- Gird and grid-scale colors can change live when switching between light and dark modes.
=> Prevent many pref panel with a caveat / live grid color change

oriedita-data/src/main/java/oriedita/editor/AnimationDurations.java, oriedita-data/src/main/java/oriedita/editor/Animations.java, oriedita-ui/src/main/java/oriedita/editor/action/ScaleAction.java, oriedita-ui/src/main/java/oriedita/editor/swing/AppMenuBar.java
- Add animation to fold scaling:
https://user-images.githubusercontent.com/94136126/225780662-70e24ce2-eac1-4999-8a93-34aea6ee9472.mp4
- Add functionality to reset the current CP view to the default view + animation (solved issue #301 ):
https://user-images.githubusercontent.com/94136126/225780768-fa3e0c14-8e48-4851-b5bc-74903243cebc.mp4
Note: @undertrox carried me throughout this whole shenanigans, I have no idea what's going on
=> Animation for fold scaling + animated reset CP view

oriedita-data/src/main/java/oriedita/editor/Colors.java, oriedita-ui/src/main/java/oriedita/editor/drawing/tools/DrawingUtil.java
1) Make the vertex fills grey and transparent for both circle & square shapes
This makes it easier to see crease pattern error with large vertices
2) Vertex fill colours made consistent between circle and square shapes 
3) Add border to square shaped vertex, again for consistency
Fixes issue #324 
Screenshots to follow shortly...
=> UI Improvements to vertex drawing

oriedita-data/src/main/java/oriedita/editor/Colors.java
See below:
Decided to opt for magenta under Light mode, as its one of the colours considered to be the inversion of yellow. Orange still looks too unclear on light background.
=> Make warning text colours clearer for both Light and Dark mode

oriedita-data/src/test/java/oriedita/editor/export/CpTest.java
If the repository is cloned on Linux with a git client, we get "\n" line endings everywhere.
If the repository is cloned on Windows with a git client, we get "\r\n" line endings everywhere.
However, if the repository is downloaded on Windows with Github's download zip feature using the web interface, then the existing files have "\n" line endings, but newly created (temporary) files e.g via automated tests have "\r\n" line endings. This causes the maven build to fail.
Fixes issue #340
=> Prevent line endings in test files from becoming inconsistent

oriedita-ui/src/main/java/oriedita/editor/swing/dialog/ExportDialog.java, oriedita-ui/src/main/java/oriedita/editor/swing/dialog/SaveTypeDialog.form, oriedita-ui/src/main/java/oriedita/editor/swing/dialog/SaveTypeDialog.java, oriedita/src/main/java/oriedita/editor/service/impl/FileSaveServiceImpl.java
Regarding to issue #316 . Import is recommended by @undertrox to be untouched and instead focus on the .FOLD for Open and Save As. Save As now as .FOLD option to pick:
And using "Open" will now show .fold files and allow users to pick them.
=> Add .FOLD option into "Save as" and allow its visibility when using "Open"

oriedita-ui/src/main/java/oriedita/editor/swing/dialog/ExportDialog.java, oriedita/src/main/java/oriedita/editor/export/Dxf.java, oriedita/src/main/java/oriedita/editor/service/impl/FileSaveServiceImpl.java
This branch focuses on implementing DXF exporting method (used in orihimeMod created by @undertrox) for AutoCAD users.
Exported .DXF file opened in Inkscape
=> DXF Export

oriedita-common/src/main/java/oriedita/editor/service/ApplicationModelPersistenceService.java, oriedita-data/src/main/java/oriedita/editor/service/FileSaveService.java, oriedita-data/src/main/java/oriedita/editor/service/impl/ApplicationModelPersistenceServiceImpl.java, oriedita-ui/src/main/java/oriedita/editor/swing/AppMenuBar.java, oriedita-ui/src/main/java/oriedita/editor/swing/dialog/PreferenceDialog.form, oriedita-ui/src/main/java/oriedita/editor/swing/dialog/PreferenceDialog.java, oriedita/src/main/java/oriedita/editor/service/impl/FileSaveServiceImpl.java
Implemented export/import tools to export settings in the preference (currently only `config.json` and `hotkey.properties`).
Clicking on export will export an `.oriconfig` file (by manually including that extension after the name) that contains the two aforementioned files.
Clicking on import will let you pick a zip file with the mandatory `.oriconfig` extension and the two files inside it will be processed.
NOTE: the two files has to have the exact name of `config.json` and `hotkey.properties` with the right content in order for it to work.
=> Import/Export settings from Preference

oriedita-data/src/main/java/oriedita/editor/canvas/CreasePattern_Worker.java, oriedita-data/src/main/java/oriedita/editor/databinding/ApplicationModel.java, oriedita-ui/src/main/java/oriedita/editor/handler/PopupMenuAdapter.java, oriedita-ui/src/main/java/oriedita/editor/swing/LeftPanel.form, oriedita-ui/src/main/java/oriedita/editor/swing/LeftPanel.java, oriedita/src/main/java/oriedita/editor/canvas/impl/CreasePattern_Worker_Impl.java, oriedita/src/main/java/oriedita/editor/handler/MouseHandlerDeleteTypeSelect.java, oriedita/src/main/java/oriedita/editor/handler/MouseHandlerReplaceSelect.java, origami/src/main/java/origami/crease_pattern/CustomLineTypes.java, origami/src/main/java/origami/crease_pattern/FoldLineSet.java
Rewrite logic for eraser and replace tool, reduce item names to mostly letter-only, and add in "M & V" option to eraser and replace-from dropdowns.
https://github.com/oriedita/oriedita/assets/94136126/f598f065-8981-47f6-b73e-c327252b7255
https://github.com/oriedita/oriedita/assets/94136126/9501fb8c-b4ba-4acb-8d4e-e87364fde2ab
Currently one slight issue is with replace-to logic, which is being prone to being manually set to ANY in file during edita runtime.
=> Rewrite eraser+replace logic / Letter-only dropdown items (mostly)

oriedita-data/src/main/java/oriedita/editor/canvas/CreasePattern_Worker.java, oriedita/src/main/java/oriedita/editor/canvas/impl/CreasePattern_Worker_Impl.java, oriedita/src/main/java/oriedita/editor/handler/MouseHandlerDeleteTypeSelect.java, oriedita/src/main/java/oriedita/editor/handler/MouseHandlerReplaceTypeSelect.java, origami/src/main/java/origami/crease_pattern/FoldLineSet.java
When using replace tool to change one line type to another, the performance drops when there are significant amount of lines (usually at about L=10000 and above), both when using click select to select a individual line segment and box select to select multiple line segments. This PR at least got around with click select by simply deleting and adding the selected segment back in, removing the need the run fix2(). 
The box select performance drop still exists and I'm currently trying to figure out how to optimize it. Please let me know if there's anything I can try because I'm running out of ideas that doesn't involve writing some new specific methods (even I don't know what those would look like).
Note: The second commit I added back in just to show that that's what it looks like at the …
=> Improve replace tool click select performance / clearer method names

oriedita-ui/src/main/java/oriedita/editor/action/ActionType.java, oriedita-ui/src/main/java/oriedita/editor/swing/LeftPanel.form, oriedita-ui/src/main/java/oriedita/editor/swing/LeftPanel.java, oriedita/src/main/java/oriedita/editor/App.java, oriedita/src/main/java/oriedita/editor/handler/MouseHandlerReplaceTypeSelect.java, oriedita/src/main/resources/help.properties, oriedita/src/main/resources/hotkey.properties, oriedita/src/main/resources/icons.properties, oriedita/src/main/resources/name.properties, oriedita/src/main/resources/tooltip.properties, origami/src/main/java/origami/crease_pattern/CustomLineTypes.java, origami/src/main/java/origami/crease_pattern/FoldLineSet.java
- Fixes the condition being written incorrectly which causes some replaces to not be possible (V -> A, MV -> M, and M -> V). Additionally I changed the name of the concerned method to `getNumberForLineColor()` to clarify that the method is only for LineColor conversion if one were to try converting value from `toLineDropBox`  ~~which come to think about it it's very bloated and inefficient lmao~~.
- Added ability to swap the two replace line types (for example M -> V to V -> M)
https://github.com/oriedita/oriedita/assets/94136126/d6e08675-90e7-4370-84d7-bcdaae8d4965
=> Replace line tool bug fix + Swap replace line types

oriedita/src/main/java/oriedita/editor/handler/MouseHandlerAxiom5.java, oriedita/src/main/java/oriedita/editor/handler/MouseHandlerAxiom7.java, oriedita/src/main/java/oriedita/editor/handler/MouseHandlerPerpendicularDraw.java, oriedita/src/main/java/oriedita/editor/handler/MouseHandlerSquareBisector.java, oriedita/src/main/java/oriedita/editor/handler/MouseHandlerSymmetricDraw.java, origami/src/main/java/origami/crease_pattern/element/LineSegment.java
- Add auto expand indicator for perpendicular tool
- Fix axiom 5's edge cases
- More responsive auto expand indicators (previously it was unclickable if near to a point/vertex, as well as being able to accidentally auto-expand immediately after selecting a line)
=> Responsive auto-expand indicator / axiom 5 fix / 2-line symmetryDraw

oriedita-data/src/main/java/oriedita/editor/databinding/CanvasModel.java, oriedita-ui/src/main/java/oriedita/editor/swing/LeftPanel.java, oriedita-ui/src/main/java/oriedita/editor/swing/RightPanel.java, oriedita/src/main/java/oriedita/editor/App.java, oriedita/src/main/java/oriedita/editor/canvas/impl/CreasePattern_Worker_Impl.java, origami/src/main/java/origami/crease_pattern/element/LineColor.java
Ctrl was used to hold-toggle swap MV for quicker drawing, but it was global and any tool that uses some kind of Ctrl+[key] key bind will trigger it. The PR's main purpose is to change that, namely setting the Ctrl usage to function differently depending on the tool being used. In this PR, Ctrl is made to swap MV for most of the drawing tools and some others, and swap replace line types for the replace line tool). Also did a few clean ups inside the LeftPanel.
=> Isolate Ctrl InputMap usage for different tools + LeftPanel clean up

oriedita/src/main/java/oriedita/editor/handler/MouseHandlerCircleDrawTangentLine.java
Added a feature for circle-circle tangent drawing tool to now also draw tangent of a circle going through a Point. 
https://github.com/oriedita/oriedita/assets/94136126/17d43bc8-6580-4521-a9af-b39424e14ccb
Select a point and a circle. Like the circle-circle tangent, you have to click on one of the purple indicators, though the indicators will now also auto expand. Note that if the selected indicator is intersecting with an existing crease, it will not auto expand and will instead draw point to point. You can also use the point-circle tangent in any order (point -> circle and circle -> point will both work).
Minor issue: VERY FEW times the point-circle tangent tool doesn't show the indicators at all and just leaves with a point segment from where you select the point. Currently unable to …
=> Point to Circle tangent

origami/src/main/java/origami/crease_pattern/OritaCalc.java
Added a LineSegment scaling method in OritaCalc...
```java
public static LineSegment getSegmentWithLength(LineSegment s0, double length){
double scaleFactor = length / s0.determineLength();
double newX = s0.determineAX() + (s0.determineBX() - s0.determineAX()) * scaleFactor;
double newY = s0.determineAY() + (s0.determineBY() - s0.determineAY()) * scaleFactor;
return new LineSegment(s0.getA(), new Point(newX, newY), s0.getColor());
}
```
... to fix auto expanding indicator inconsistency (at least hopefully I don't really see any problem with it yet). @JuhoKonkkola you can test this if you don't mind.
=> Improve auto expand by implementing a LineSegment scaling method

oriedita-common/src/main/java/oriedita/common/task/MultiStagedExecutor.java, oriedita-common/src/main/java/oriedita/editor/tools/ResourceUtil.java, oriedita-ui/src/main/java/oriedita/editor/swing/BottomPanel.java, oriedita-ui/src/main/java/oriedita/editor/swing/Editor.java, oriedita-ui/src/main/java/oriedita/editor/swing/component/FoldedFigureResize.java, oriedita-ui/src/main/java/oriedita/editor/swing/component/FoldedFigureRotate.java, oriedita-ui/src/main/java/oriedita/editor/swing/dialog/LoadingDialog.java, oriedita/src/main/java/oriedita/editor/App.java, oriedita/src/main/java/oriedita/editor/Oriedita.java, oriedita/src/main/java/oriedita/editor/canvas/impl/CreasePattern_Worker_Impl.java, oriedita/src/main/resources/tinylog.properties
Improves startup performance in the following ways:
- Run main startup from the main thread, this also makes sure that the first render of the main frame is actually correct and does not flash a wrong layout
- Multithread every non-ui setup task
Multithreading is done in multiple stages (see `App.start()`)
1. Initialize the editor, this registers buttons and adds action listeners (multithreaded)
2. Configure the main frame
3. Configure property change listeners in the model
4. Reset the UI state based on the model (multithreaded)
5. Pack main frame and correct position
=> Improve startup performance

oriedita-data/src/main/java/oriedita/editor/databinding/ApplicationModel.java, oriedita-ui/src/main/java/oriedita/editor/action/ActionType.java, oriedita-ui/src/main/java/oriedita/editor/swing/dialog/PreferenceDialog.java, oriedita/src/main/java/oriedita/editor/canvas/impl/CreasePattern_Worker_Impl.java, oriedita/src/main/java/oriedita/editor/service/ActionRegistrationService.java
- Changes towards applicationModel and foldedFigureModel in other panels like LeftPanel are now auto-reflected into the preference dialog while it's opened.
- Change to default grid (line and interval) colors in preference dialog
- Change pref's default operation on close to actually dispose instead of hide to fix it not closing properly
- Fix some warnings and change an iterator during tool list updating
- Set all changes in line width (mainly in LeftPanel and RightPanel) to use increment/decrement of 1
- Fix marker aux eraser button not working
- Simplify methods in ApplicationModel
=> More pref Dialog updates (and other changes)

oriedita-ui/src/main/java/oriedita/editor/action/ActionType.java, oriedita-ui/src/main/java/oriedita/editor/action/ConvertAction.java, oriedita-ui/src/main/java/oriedita/editor/swing/AppMenuBar.java
Ability to choose one file at a time to convert from a crease pattern type to another (example: .cp to .ori). Currently it supports CP, ORI, ORH, and FOLD as these already their own importer and exporters.
> [!NOTE]  
> Writing the file might be a bit weird due to naming with/without extension, different OS with different file explorer, ... However this shouldn't be a major issue. Currently this can only select one file at a time as AWT hates us; in the future it should be able to select a folder so it can go thru the files and deal with them one by one.
=> Convert single crease pattern file type into another type

oriedita-ui/src/main/java/oriedita/editor/swing/dialog/SaveTypeDialog.form, oriedita-ui/src/main/java/oriedita/editor/swing/dialog/SaveTypeDialog.java
to avoid confusion mainly (it might benefit having grid info like .ori but that's for later time).
=> Change .FOLD saving description

oriedita-ui/src/main/java/oriedita/editor/swing/dialog/PreferenceDialog.java
This PR fixes the garbled characters appearing in the preference dialog (only for Asian language PCs perhaps):
The source of this issue is because categories.csv is encoded under UTF-8 with BOM. Here I add checking to the input stream, so that it will correctly read the csv file, with or without BOM (as we don't want to make assumptions on whoever is editing the csv file).
=> Fix garbled characters in preference dialog

origami/src/main/java/origami/crease_pattern/PointSet.java
The calculating face patches seem to be causing issues with folding (showing wireframe in colored fold when it's not supposed to). Those patches will be pull backed for now to investigate a bit more properly.
With that being said, if you're using the latest build from this PR going forward, please make sure to backup your file in a different format like `.ori`, or refer to the auto-save folder as it might save your working file there if it does get wiped out when saving/exporting failed.
=> Temporarily revert #440 and #448 for debugging

oriedita/src/main/java/oriedita/editor/handler/MouseHandlerDrawCreaseAngleRestricted.java, oriedita/src/main/java/oriedita/editor/tools/SnappingUtil.java, origami/src/main/java/origami/Epsilon.java, origami/src/main/java/origami/crease_pattern/FoldLineSet.java, origami/src/main/java/origami/crease_pattern/OritaCalc.java, origami/src/main/java/origami/crease_pattern/element/StraightLine.java, origami/src/main/java/origami/crease_pattern/worker/foldlineset/Check1.java, origami/src/main/java/origami/crease_pattern/worker/foldlineset/Check2.java, origami/src/main/java/origami/crease_pattern/worker/foldlineset/Fix1.java, origami/src/main/java/origami/crease_pattern/worker/foldlineset/Fix2.java
This PR doubles the precision for point comparison, fixing folding errors found in some of the CPs.
It also completely determines the meaning of all `Epsilon.UNKNOWN_01` and gives them proper names.
=> Double the precision for comparing points

oriedita/src/main/java/oriedita/editor/service/impl/SingleTaskExecutorServiceImpl.java
The cause of the issue is that some fields in `SingleTaskExecutorServiceImpl` are declared `static`, resulting in camvExecutor stopping foldingExecutor.
=> Fix folding when selecting from CP

oriedita/src/main/java/oriedita/editor/App.java
There's no reason for app being minimized or not to be saved for the next relaunch. It's also somehow causing the problem (at least on MacOS) which this PR aims to fix.
=> Fix app not minimizing on Mac

oriedita-ui/src/main/java/oriedita/editor/swing/AppMenuBar.java, oriedita/src/main/java/oriedita/editor/service/impl/FileSaveServiceImpl.java
Initial behavior for that scenario is that nothing happens, no indication whatsoever even though the dialog itself is implemented. `openFile()` simply returns if a file doesn't exist, so it was never caught. For the same reason, opening a non-existent file will also delete the item with the file path in the recent files list.
I haven't tested this much and it might affect how the message is displayed in the dialog for other kinds of exceptions meant for the original implementation (but I doubt it will be an issue). Please review this and let me know for any concern.
=> Show dialog for when recent file doesn't exist
